; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
core_dir = C:/git/.platformio

[env:Fetcher]
platform = espressif32@6.12.0
board = wemos_d1_mini32
board_build.f_cpu = 120000000L   ; Low power CPU frequency (120MHz)
board_build.f_flash = 40000000L
board_build.partitions = partitions.csv
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_protocol = esptool
upload_resetmethod = nodemcu
upload_port = COM6
monitor_port = COM6
monitor_filters = esp32_exception_decoder
lib_deps = 
	tzapu/WiFiManager@^2.0.17
	tobozo/ESP32-targz@^1.2.2
	hideakitai/ESP32SPISlave@^0.6.3
lib_ignore = 
	EPaper
	GUI
	Examples
	Fonts
	RTC
build_flags = 
	-DARDUINO_LOOP_STACK_SIZE=81920
	-DARDUINO_SPI_SLAVE_STACK_SIZE=65536
	-DBOARD_HAS_PSRAM=0
	-DCONFIG_FREERTOS_UNICORE=1     ; Run on single core for power saving
build_src_filter = +<fetcher.cpp>

[env:Fetcher8266]
platform = espressif8266@4.2.1
board = esp01
board_build.f_cpu = 80000000L
board_build.f_flash = 40000000L
board_build.ldscript = eagle.flash.1m256.ld
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_protocol = esptool
upload_resetmethod = nodemcu
upload_port = COM6
monitor_port = COM6
monitor_filters = esp32_exception_decoder
lib_deps = 
	tzapu/WiFiManager@^2.0.17
	tobozo/ESP32-targz@^1.2.2
	hideakitai/ESP32SPISlave@^0.6.3
	Preferences@^2.2.2
lib_ignore = 
	EPaper
	GUI
	Examples
	Fonts
	RTC
build_flags = 
	-DARDUINO_LOOP_STACK_SIZE=81920
	-DARDUINO_SPI_SLAVE_STACK_SIZE=65536
	-DBOARD_HAS_PSRAM=0
	-DCONFIG_FREERTOS_UNICORE=1     ; Run on single core for power saving
build_src_filter = +<fetcher.cpp>

[env:Renderer]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#a1df30f
board = pico
framework = arduino
board_build.mcu = rp2040
board_build.f_cpu = 40000000L
board_build.core = earlephilhower
monitor_speed = 115200
upload_protocol = custom
upload_port = COM7
monitor_port = COM7
upload_command = utils\pico_upload.bat $SOURCE $UPLOAD_PORT
build_flags = 
	-DUSE_TINYUSB
	-DPICO_ENABLE_STDIO_USB=1
	-DPICO_ENABLE_WATCHDOG=1
    -DPICO_STDIO_USB_ENABLE_RESET_VIA_VENDOR_INTERFACE=1
	-I lib/Config/src
	-I lib/Examples/src
	-I lib/LED/src
	-I lib/RTC/src
lib_deps = 
	Config@^1.0.0
	LED@^1.0.0
	Examples@^1.0.0
	RTC@^1.0.0
build_src_filter = +<renderer.cpp>
